# Generic production config.
# Copied to config.yml if needed by lute.main

ENV: dev
DBNAME: test_lute.db
DATAPATH: /home/fan/lutedata/test

# DATAPATH is not set: user data should be
# stored in PlatformDirs.user_data_dir
# (ref https://pypi.org/project/platformdirs/).

# BACKUP_PATH is not set, user should choose.
